HT_Q1

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Cutlets.csv to Cutlets.csv


In [ ]:
import pandas as pd
from scipy import stats

In [ ]:
cutlets = pd.read_csv('/content/Cutlets.csv')
cutlets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [ ]:
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
unitA = pd.Series(cutlets.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [ ]:
unitB = pd.Series(cutlets.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [ ]:
stats.ttest_ind(unitA, unitB)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

HT_Q2

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving LabTAT.csv to LabTAT.csv


In [ ]:
import pandas as pd
from scipy import stats

In [ ]:
Labtat = pd.read_csv('/content/LabTAT.csv')
Labtat

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [ ]:
LabA = pd.Series(Labtat.iloc[:,0])
LabA

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...  
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [ ]:
LabB = pd.Series(Labtat.iloc[:,1])
LabB

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [ ]:
LabC = pd.Series(Labtat.iloc[:,2])
LabC

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...  
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [ ]:
LabD = pd.Series(Labtat.iloc[:,3])
LabD

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [ ]:
stats.f_oneway(LabA, LabB, LabC, LabD)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

HT_Q3

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving BuyerRatio.csv to BuyerRatio (1).csv


In [ ]:
import pandas as pd
from scipy import stats
from scipy.stats import chi2_contingency

In [ ]:
df = pd.read_csv('/content/BuyerRatio (1).csv')
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64 
 2   West             2 non-null      int64 
 3   North            2 non-null      int64 
 4   South            2 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes


In [ ]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
Male = pd.Series(df.iloc[0, 1:])
Male

East      50
West     142
North    131
South     70
Name: 0, dtype: object

In [ ]:
Female = pd.Series(df.iloc[1, 1:])
Female

East      435
West     1523
North    1356
South     750
Name: 1, dtype: object

In [ ]:
array = (Male, Female)
array

(East      50
 West     142
 North    131
 South     70
 Name: 0, dtype: object, East      435
 West     1523
 North    1356
 South     750
 Name: 1, dtype: object)

In [ ]:
chi2_contingency(array)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

HT_Q4

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm.csv


In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
COF = pd.read_csv('Costomer+OrderForm.csv')

In [ ]:
COF.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [ ]:
COF['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [ ]:
COF['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [ ]:
COF['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [ ]:
COF['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [ ]:
COF = np.array([[271,267,269,280],[29,33,31,20]])
COF

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [ ]:
stats.chi2_contingency(COF)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))